# reguly oceniana tekstow w zaleznosci od liczby wystepujacych rol
rules = {
    ('cel', 'zdarzenie', 'sprawca', 'narzedzie', 'miejsce', 'obiekt'): 1.0,
    ('zdarzenie', 'sprawca', 'narzedzie', 'miejsce', 'obiekt'): 0.95,
    ('cel', 'sprawca', 'narzedzie', 'miejsce', 'obiekt'): 0.95,
    ('cel', 'zdarzenie', 'narzedzie', 'miejsce', 'obiekt'): 0.95,
    ('cel', 'zdarzenie', 'sprawca', 'miejsce', 'obiekt'): 0.85,
    ('cel', 'zdarzenie', 'sprawca', 'narzedzie', 'obiekt'): 0.95,
    ('cel', 'zdarzenie', 'sprawca', 'narzedzie', 'miejsce'): 0.95,
    ('cel', 'zdarzenie', 'sprawca', 'narzedzie'): 0.8,
    ('cel', 'zdarzenie', 'sprawca', 'miejsce'): 0.7,
    ('cel', 'zdarzenie', 'sprawca', 'obiekt'): 0.8,
    ('cel', 'zdarzenie', 'narzedzie', 'miejsce'): 0.8,
    ('cel', 'zdarzenie', 'narzedzie', 'obiekt'): 0.9,
    ('cel', 'zdarzenie', 'miejsce', 'obiekt'): 0.65,
    ('cel', 'sprawca', 'narzedzie', 'miejsce'): 0.8,
    ('cel', 'sprawca', 'narzedzie', 'obiekt'): 0.85,
    ('cel', 'sprawca', 'miejsce', 'obiekt'): 0.75,
    ('cel', 'narzedzie', 'miejsce', 'obiekt'): 0.85,
    ('zdarzenie', 'sprawca', 'narzedzie', 'miejsce'): 0.8,
    ('zdarzenie', 'sprawca', 'narzedzie', 'obiekt'): 0.85,
    ('zdarzenie', 'sprawca', 'miejsce', 'obiekt'): 0.7,
    ('zdarzenie', 'narzedzie', 'miejsce', 'obiekt'): 0.75,
    ('sprawca', 'narzedzie', 'miejsce', 'obiekt'): 0.8,
    ('cel', 'zdarzenie', 'sprawca'): 0.65,
    ('cel', 'zdarzenie', 'narzedzie'): 0.7,
    ('cel', 'zdarzenie', 'miejsce'): 0.6,
    ('cel', 'zdarzenie', 'obiekt'): 0.6,
    ('cel', 'sprawca', 'narzedzie'): 0.7,
    ('cel', 'sprawca', 'miejsce'): 0.55,
    ('cel', 'sprawca', 'obiekt'): 0.65,
    ('cel', 'narzedzie', 'miejsce'): 0.65,
    ('cel', 'narzedzie', 'obiekt'): 0.75,
    ('cel', 'miejsce', 'obiekt'): 0.7,
    ('zdarzenie', 'sprawca', 'narzedzie'): 0.7,
    ('zdarzenie', 'sprawca', 'miejsce'): 0.45,
    ('zdarzenie', 'sprawca', 'obiekt'): 0.65,
    ('zdarzenie', 'narzedzie', 'miejsce'): 0.7,
    ('zdarzenie', 'narzedzie', 'obiekt'): 0.75,
    ('zdarzenie', 'miejsce', 'obiekt'): 0.6,
    ('sprawca', 'narzedzie', 'miejsce'): 0.65,
    ('sprawca', 'narzedzie', 'obiekt'): 0.7,
    ('sprawca', 'miejsce', 'obiekt'): 0.6,
    ('narzedzie', 'miejsce', 'obiekt'): 0.7,
    ('cel', 'zdarzenie'): 0.4,
    ('cel', 'sprawca'): 0.4,
    ('cel', 'narzedzie'): 0.6,
    ('cel', 'miejsce'): 0.35,
    ('cel', 'obiekt'): 0.55,
    ('zdarzenie', 'sprawca'): 0.45,
    ('zdarzenie', 'narzedzie'): 0.55,
    ('zdarzenie', 'miejsce'): 0.35,
    ('zdarzenie', 'obiekt'): 0.45,
    ('sprawca', 'narzedzie'): 0.65,
    ('sprawca', 'miejsce'): 0.35,
    ('sprawca', 'obiekt'): 0.4,
    ('narzedzie', 'miejsce'): 0.4,
    ('narzedzie', 'obiekt'): 0.6,
    ('miejsce', 'obiekt'): 0.65,
    ('cel',): 0.1,
    ('zdarzenie',): 0.1,
    ('sprawca',): 0.2,
    ('narzedzie',): 0.3,
    ('miejsce',): 0.1,
    ('obiekt',): 0.2,
}
